let neighborhoods = {
  'Alcides Rabelo': 1,
  'Alto da Boa Vista': 1,
  'Augusta Mota': 1,
  'Canelas I e II': 1,
  'Carmelo': 1,
  'Clarice Ataíde': 1,
  'Clarindo Lopes': 1,
  'Conj. Havaí': 1,
  'Conjunto José Carlos de Lima': 1,
  'Delfino Magalhães': 1,
  'Dr. Antônio Pimenta': 1,
  'Dr. João Alves': 1,
  'Esplanada': 1,
  'Francisco Perez': 1,
  'Guarujá': 1,
  'Jaraguá I': 1,
  'Jardim Alegre': 1,
  'Jardim Liberdade': 1,
  'Jardim Palmeiras': 1,
  'Jardim Primavera': 1,
  'Jardim São Geraldo': 1,
  'João Botelho': 1,
  'JK': 1,
  'Major Prates': 1,
  'Maria Cândida': 1,
  'Monte Carmelo': 1,
  'Morada da Serra': 1,
  'Morada do Parque': 1,
  'Nova América': 1,
  'Parque Jardim Morada do Sol': 1,
  'Planalto': 1,
  'Raul Lourenço': 1,
  'Recanto das Águas': 1,
  'Regina Peres': 1,
  'Residencial Minas Gerais': 1,
  'Residencial Monte Cristal': 1,
  'Residencial Monte Fiore': 1,
  'Santa Laura': 1,
  'Santa Lucia I e II': 1,
  'Santa Rita I e II': 1,
  'Santo Antônio I': 1,
  'São Lucas': 1,
  'Universitário': 1,
  'Vargem Grande II': 1,
  'Vila Sion': 1,
  'Vila Telma': 1,
  'Vilage do Lago l e II': 1,
  'Acácia': 2,
  'Alterosa': 2,
  'Amazonas': 2,
  'Centro': 2,
  'Chiquinho Guimarães': 2,
  'Cidade Industrial': 2,
  'Ciro dos Anjos': 2,
  'Conjunto Habitacional Joaquim Costa': 2,
  'Cristo Rei': 2,
  'Dona Gregória': 2,
  'Edgar Pereira': 2,
  'Independência e Adjacentes': 2,
  'Interlagos': 2,
  'Jaraguá II': 2,
  'Jardim Brasil': 2,
  'José Corrêa Machado': 2,
  'Mangues': 2,
  'Maracanã': 2,
  'Melo': 2,
  'Nossa Senhora das Graças': 2,
  'Nova Suíça': 2,
  'Novo Jaraguá': 2,
  'Residencial Vitória I e II': 2,
  'Santa Rafaela': 2,
  'Santo Inácio': 2,
  'Santos Dumont': 2,
  'Santos Reis': 2,
  'São Bento': 2,
  'São Judas I': 2,
  'Todos os Santos': 2,
  'Vila Antônio Narciso': 2,
  'Vila Áurea': 2,
  'Vila Brasília': 2,
  'Vila Campos': 2,
  'Vila Greicy': 2,
  'Vila João Gordo': 2,
  'Vila Nossa Senhora Aparecida': 2,
  'Vila Real': 2,
  'Vila Santa Cruz': 2,
  'Vila São Francisco de Assis': 2,
  'Alice Maia': 3,
  'Alto São João': 3,
  'Barcelona Park': 3,
  'Bela Vista': 3,
  'Belvedere': 3,
  'Camilo Prates': 3,
  'Cândida Câmara': 3,
  'Cintra': 3,
  'Eldorado': 3,
  'Fazendas': 3,
  'Floresta': 3,
  'Funcionários': 3,
  'Gran Royalle Pirâmide': 3,
  'Ibituruna': 3,
  'Jardim Alvorada': 3,
  'Jardim Europa': 3,
  'Jardim Olímpico': 3,
  'Jardim São Luiz': 3,
  'Lurdes': 3,
  'Monte Alegre': 3,
  'Morada do Sol': 3,
  'Nossa Senhora de Fátima': 3,
  'Nova Morada': 3,
  'Novo Delfino': 3,
  'Olga Benário': 3,
  'Panorama I e II': 3,
  'Parque jardim Olímpico': 3,
  'Ponta do Morro': 3,
  'Renascença': 3,
  'Residencial Montes Claros': 3,
  'Residencial Sul e Sul Ipês': 3,
  'Residencial Vila do Cedro': 3,
  'Roxo Verde': 3,
  'Sagrada Família': 3,
  'Santa Cecília': 3,
  'Santa Eugênia': 3,
  'Santo Amaro': 3,
  'Santo Antônio ll': 3,
  'São Geraldo ll': 3,
  'São José': 3,
  'São Judas II': 3,
  'Sumaré': 3,
  'Tancredo Neves': 3,
  'Todos os Santos II': 3,
  'Vera Cruz': 3,
  'Vila Anália': 3,
  'Vila Atlântida': 3,
  'Vila Castelo Branco': 3,
  'Vila Exposição': 3,
  'Vila Ipiranga': 3,
  'Vila Mauricéia': 3,
  'Vila Oliveira': 3,
  'Vila Santa Maria': 3,
  'Vila Regina': 3,
  'Vila Tiradentes': 3,
  'Cidade Nova': 4,
  'Distrito Industrial': 4,
  'Vila Guilhermina e adjacências': 4
}
