account_id = "779f26d6062518fa03d78247becfd24c"
name = "temagua"
type = "webpack"
workers_dev = true

[site]
bucket = "dist"
entry-point = "workers-site"

[env.production]
route = "temagua.myhro.info/*"
workers_dev = false
zone_id = "dbe71f84a9e980bcfd36c2f2fda5e825"
