account_id = "779f26d6062518fa03d78247becfd24c"
kv-namespaces = [
  { binding = "DB", id = "6279e78b38424e549b5fbd4754831915" }
]
name = "temagua-api"
route = "temagua-api.myhro.net/*"
type = "webpack"
webpack_config = "webpack.production.js"
workers_dev = false
zone_id = "61d51546beb0253d7f4c005cb3bf7749"

[env.production]
kv-namespaces = [
  { binding = "DB", id = "088c359c269a432cad3d815c326fc977" }
]
route = "temagua-api.myhro.info/*"
webpack_config = "webpack.production.js"
zone_id = "dbe71f84a9e980bcfd36c2f2fda5e825"
