account_id = "779f26d6062518fa03d78247becfd24c"
kv-namespaces = [
  { binding = "DB", id = "6279e78b38424e549b5fbd4754831915" }
]
name = "temagua-api"
type = "javascript"
workers_dev = true

[env.production]
kv-namespaces = [
  { binding = "DB", id = "088c359c269a432cad3d815c326fc977" }
]
route = "temagua-api.myhro.info/*"
workers_dev = false
zone_id = "dbe71f84a9e980bcfd36c2f2fda5e825"
