name: API
on: [push]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Check
        run: |
          cd api/
          make deps
          make check
          make lint
  test:
    needs: check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Test
        run: |
          make restore
          make dump
          cd api/
          make deps
          make test
