name: API
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
      - name: Test
        run: make test
