name: Feed
on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  Deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd feed/
          make deps
          make deploy
  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'schedule'
    needs: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Deploy Production
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd feed/
          make deps
          make deploy-prod
