name: Site
on: [push]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Check
        run: |
          cd site/
          make deps
          make check
          make lint
  build:
    needs: check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build
        run: |
          cd site/
          make deps
          make build
